apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app
type: Opaque
stringData:
  DB_HOST: postgres-service.data.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: tech_pay_scale_db
  DB_USER: admin
  DB_PASSWORD: