apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: identity-service
          image: techsalaryregistry.azurecr.io/identity_service:v1
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10