apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: app
spec:
  selector:
    app: identity-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP