apiVersion: apps/v1
kind: Deployment
metadata:
  name: salary-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: salary-service
  template:
    metadata:
      labels:
        app: salary-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: salary-service
          image: techsalaryregistry.azurecr.io/salary_service:v1
          imagePullPolicy: Always  # always pull the latest image for this tag
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 30