apiVersion: v1
kind: Service
metadata:
  name: stats_service
  namespace: app
spec:
  selector:
    app: stats_service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP