"""update_models_to_uuid_and_add_fields

Revision ID: 3539f20b750c
Revises: 6fafd3b93624
Create Date: 2026-03-21 11:31:39.634984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3539f20b750c'
down_revision: Union[str, Sequence[str], None] = '6fafd3b93624'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('vote_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='community'
    )
    op.create_index(op.f('ix_community_votes_submission_id'), 'votes', ['submission_id'], unique=False, schema='community')
    op.create_index(op.f('ix_community_votes_user_id'), 'votes', ['user_id'], unique=False, schema='community')
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('company', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('anonymize_flag', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='salary'
    )
    op.create_index(op.f('ix_salary_submissions_company'), 'submissions', ['company'], unique=False, schema='salary')
    op.create_index(op.f('ix_salary_submissions_country'), 'submissions', ['country'], unique=False, schema='salary')
    op.create_index(op.f('ix_salary_submissions_experience_level'), 'submissions', ['experience_level'], unique=False, schema='salary')
    op.create_index(op.f('ix_salary_submissions_role'), 'submissions', ['role'], unique=False, schema='salary')
    op.create_index(op.f('ix_salary_submissions_status'), 'submissions', ['status'], unique=False, schema='salary')
    op.drop_index(op.f('ix_salary_salaries_id'), table_name='salaries', schema='salary')
    op.drop_index(op.f('ix_salary_salaries_user_id'), table_name='salaries', schema='salary')
    op.drop_table('salaries', schema='salary')
    op.drop_index(op.f('ix_community_comments_id'), table_name='comments', schema='community')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='comments', schema='community')
    op.drop_table('comments', schema='community')
    op.add_column('users', sa.Column('username', sa.String(), nullable=False), schema='identity')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'),
               schema='identity')
    op.drop_constraint(op.f('users_email_key'), 'users', schema='identity', type_='unique')
    op.create_index(op.f('ix_identity_users_email'), 'users', ['email'], unique=True, schema='identity')
    op.create_index(op.f('ix_identity_users_user_id'), 'users', ['user_id'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_users_username'), 'users', ['username'], unique=True, schema='identity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_users_username'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_user_id'), table_name='users', schema='identity')
    op.drop_index(op.f('ix_identity_users_email'), table_name='users', schema='identity')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='identity', postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'),
               schema='identity')
    op.drop_column('users', 'username', schema='identity')
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey')),
    schema='community'
    )
    op.create_index(op.f('ix_community_comments_post_id'), 'comments', ['post_id'], unique=False, schema='community')
    op.create_index(op.f('ix_community_comments_id'), 'comments', ['id'], unique=False, schema='community')
    op.create_table('salaries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('job_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('annual_base_salary', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('years_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('salaries_pkey')),
    schema='salary'
    )
    op.create_index(op.f('ix_salary_salaries_user_id'), 'salaries', ['user_id'], unique=False, schema='salary')
    op.create_index(op.f('ix_salary_salaries_id'), 'salaries', ['id'], unique=False, schema='salary')
    op.drop_index(op.f('ix_salary_submissions_status'), table_name='submissions', schema='salary')
    op.drop_index(op.f('ix_salary_submissions_role'), table_name='submissions', schema='salary')
    op.drop_index(op.f('ix_salary_submissions_experience_level'), table_name='submissions', schema='salary')
    op.drop_index(op.f('ix_salary_submissions_country'), table_name='submissions', schema='salary')
    op.drop_index(op.f('ix_salary_submissions_company'), table_name='submissions', schema='salary')
    op.drop_table('submissions', schema='salary')
    op.drop_index(op.f('ix_community_votes_user_id'), table_name='votes', schema='community')
    op.drop_index(op.f('ix_community_votes_submission_id'), table_name='votes', schema='community')
    op.drop_table('votes', schema='community')
    # ### end Alembic commands ###
