"""Initial schema

Revision ID: 6fafd3b93624
Revises: 
Create Date: 2026-03-04 00:54:25.131476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fafd3b93624'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='community'
    )
    op.create_index(op.f('ix_community_comments_id'), 'comments', ['id'], unique=False, schema='community')
    op.create_index(op.f('ix_community_comments_post_id'), 'comments', ['post_id'], unique=False, schema='community')
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='identity'
    )
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('annual_base_salary', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='salary'
    )
    op.create_index(op.f('ix_salary_salaries_id'), 'salaries', ['id'], unique=False, schema='salary')
    op.create_index(op.f('ix_salary_salaries_user_id'), 'salaries', ['user_id'], unique=False, schema='salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_salaries_user_id'), table_name='salaries', schema='salary')
    op.drop_index(op.f('ix_salary_salaries_id'), table_name='salaries', schema='salary')
    op.drop_table('salaries', schema='salary')
    op.drop_table('users', schema='identity')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='comments', schema='community')
    op.drop_index(op.f('ix_community_comments_id'), table_name='comments', schema='community')
    op.drop_table('comments', schema='community')
    # ### end Alembic commands ###
